name: Docs

on:
  workflow_call:
    inputs:
      changed-files:
        required: true
        type: string
        description: JSON string containing information about changed files

jobs:
  docs:
    name: Build Relenv Documentation
    runs-on: ubuntu-24.04

    steps:
      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install System Deps
        run: |
          sudo apt-get update
          sudo apt-get install -y enchant-2 git gcc imagemagick make zlib1g-dev libc-dev libffi-dev g++ libxml2 libxml2-dev libxslt-dev libcurl4-openssl-dev libssl-dev libgnutls28-dev xz-utils

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Nox
        run: |
          python -m pip install --upgrade pip
          pip install nox ppbt

      - name: Build Docs
        run: |
          nox --forcecolor -e docs

      - name: Store Generated Documentation
        uses: actions/upload-artifact@v4
        with:
          name: relenv-html-docs
          path: docs/build
